const tableData = [
  {
    title: 'Rational prescription',
    identity: 'AMBU',
    type: 'internal',
    garant: 'Milan',
    status: 'Active',
  },
  {
    title: 'Patient monitoring system',
    identity: 'CARD',
    type: 'external',
    garant: 'Sarah',
    status: 'Draft',
  },
  {
    title: 'Emergency protocol',
    identity: 'ER',
    type: 'internal',
    garant: 'John',
    status: 'Awaiting',
  },
  {
    title: 'Medical supplies inventory',
    identity: 'INV',
    type: 'internal',
    garant: 'Emma',
    status: 'Inactive',
  },
  {
    title: 'Staff rotation schedule',
    identity: 'HR',
    type: 'internal',
    garant: 'Michael',
    status: 'Active',
  },
  {
    title: 'Lab results management',
    identity: 'LAB',
    type: 'external',
    garant: 'Laura',
    status: 'Draft',
  },
  {
    title: 'Patient education materials',
    identity: 'EDU',
    type: 'internal',
    garant: 'Robert',
    status: 'Awaiting',
  },
  {
    title: 'Health insurance protocol',
    identity: 'INS',
    type: 'external',
    garant: 'Jennifer',
    status: 'Inactive',
  },
  {
    title: 'Vaccination program',
    identity: 'VAC',
    type: 'internal',
    garant: 'David',
    status: 'Active',
  },
  {
    title: 'Medical equipment maintenance',
    identity: 'EQ',
    type: 'external',
    garant: 'Linda',
    status: 'Draft',
  },
  {
    title: 'Research protocol',
    identity: 'RES',
    type: 'internal',
    garant: 'James',
    status: 'Awaiting',
  },
  {
    title: 'Quality management system',
    identity: 'QMS',
    type: 'internal',
    garant: 'Patricia',
    status: 'Inactive',
  },
  {
    title: 'Patient discharge guidelines',
    identity: 'DCH',
    type: 'internal',
    garant: 'Thomas',
    status: 'Active',
  },
  {
    title: 'Telemedicine implementation',
    identity: 'TELE',
    type: 'external',
    garant: 'Susan',
    status: 'Draft',
  },
  {
    title: 'Pharmaceuticals procurement',
    identity: 'PHARM',
    type: 'internal',
    garant: 'Richard',
    status: 'Awaiting',
  },
  {
    title: 'Disease prevention protocol',
    identity: 'PREV',
    type: 'internal',
    garant: 'Karen',
    status: 'Inactive',
  },
  {
    title: 'Staff training program',
    identity: 'TRN',
    type: 'internal',
    garant: 'Charles',
    status: 'Active',
  },
  {
    title: 'IT systems security',
    identity: 'IT',
    type: 'external',
    garant: 'Lisa',
    status: 'Draft',
  },
  {
    title: 'Clinical trials management',
    identity: 'CTM',
    type: 'internal',
    garant: 'William',
    status: 'Awaiting',
  },
  {
    title: 'Medical waste handling',
    identity: 'WASTE',
    type: 'external',
    garant: 'Nancy',
    status: 'Inactive',
  },
  {
    title: 'Infection control procedures',
    identity: 'INF',
    type: 'internal',
    garant: 'Kevin',
    status: 'Active',
  },
  {
    title: 'Organ donation protocol',
    identity: 'ORG',
    type: 'internal',
    garant: 'Betty',
    status: 'Draft',
  },
  {
    title: 'Rehabilitation program',
    identity: 'REHAB',
    type: 'internal',
    garant: 'Mark',
    status: 'Awaiting',
  },
  {
    title: 'Mental health services',
    identity: 'MH',
    type: 'external',
    garant: 'Sandra',
    status: 'Inactive',
  },
  {
    title: 'Pandemic response plan',
    identity: 'PAND',
    type: 'internal',
    garant: 'Joseph',
    status: 'Active',
  },
  {
    title: 'Maternal care guidelines',
    identity: 'MAT',
    type: 'internal',
    garant: 'Ruth',
    status: 'Draft',
  },
  {
    title: 'Palliative care protocol',
    identity: 'PAL',
    type: 'internal',
    garant: 'Edward',
    status: 'Awaiting',
  },
  {
    title: 'Emergency evacuation plan',
    identity: 'EVAC',
    type: 'internal',
    garant: 'Helen',
    status: 'Inactive',
  },
  {
    title: 'Community health outreach',
    identity: 'COM',
    type: 'external',
    garant: 'Jason',
    status: 'Active',
  },
];

const table1Data = [
  {
    title: 'Patient care guidelines',
    identity: 'PCG',
    type: 'internal',
    garant: 'Daniel',
    status: 'Active',
  },
  {
    title: 'Electronic health records',
    identity: 'EHR',
    type: 'external',
    garant: 'Margaret',
    status: 'Awaiting',
  },
  {
    title: 'Nutrition assessment',
    identity: 'NUT',
    type: 'internal',
    garant: 'Christopher',
    status: 'Draft',
  },
  {
    title: 'Blood bank management',
    identity: 'BBM',
    type: 'internal',
    garant: 'Angela',
    status: 'Inactive',
  },
  {
    title: 'Pediatric care protocol',
    identity: 'PED',
    type: 'internal',
    garant: 'Steven',
    status: 'Awaiting',
  },
  {
    title: 'Surgical procedures manual',
    identity: 'SURG',
    type: 'internal',
    garant: 'Kimberly',
    status: 'Active',
  },
  {
    title: 'Radiology guidelines',
    identity: 'RAD',
    type: 'external',
    garant: 'Brian',
    status: 'Inactive',
  },
  {
    title: 'Laboratory safety protocol',
    identity: 'LSAFE',
    type: 'internal',
    garant: 'Dorothy',
    status: 'Active',
  },
  {
    title: 'Healthcare IT infrastructure',
    identity: 'HIT',
    type: 'external',
    garant: 'Matthew',
    status: 'Active',
  },
  {
    title: 'Diagnostic imaging workflow',
    identity: 'DIAG',
    type: 'internal',
    garant: 'Olivia',
    status: 'Draft',
  },
];

const table2Data = [
  {
    title: 'Hospital accreditation standards',
    identity: 'ACCR',
    type: 'internal',
    garant: 'George',
    status: 'Active',
  },
  {
    title: 'Efficient workflow optimization',
    identity: 'WF',
    type: 'external',
    garant: 'Emily',
    status: 'Draft',
  },
  {
    title: 'Project management methodology',
    identity: 'PM',
    type: 'internal',
    garant: 'Sarah',
    status: 'Awaiting',
  },
  {
    title: 'Customer support system',
    identity: 'CS',
    type: 'external',
    garant: 'Andrew',
    status: 'Inactive',
  },
];

const transformedDataCSCTabs = table2Data.map((item) => ({
  name: item.title,
  type: item.type,
  status: item.status,
  validUntil: '21.12.2024',
}));

export { table1Data, table2Data, tableData, transformedDataCSCTabs };
