module.exports = {
  success: {
    state: 'Success',
    messages: [],
    payload: {
      total: 14,
      items: [
        {
          id: 'ba7fc612-ce09-4053-a456-c21afa56c363',
          description: 'Nůžky',
          categoryType: 'Operations',
          sapNumber: 'SAP123456789',
          supplierArticleNumber: 'NUZ-01',
          unitOfMeasure: 'Ks',
          unitPrice: 239.5,
          isFavorite: true,
          contract: 'SMLOUVA-2024-032',
          externalUrl: '',
          attachments: [],
        },
        {
          id: 'qn1tu056-pq32-7386-o789-q54otu90r707',
          description: 'Nůžky kancelářské',
          categoryType: 'Operations',
          sapNumber: '000000000300002783',
          supplierArticleNumber: 'NUZ-KANC-01',
          unitOfMeasure: 'Ks',
          unitPrice: 145,
          isFavorite: false,
          contract: 'SMLOUVA-2024-032',
          externalUrl: '',
          attachments: [],
        },
        {
          id: 'ro2uv167-qr43-8497-p890-r65puv01s818',
          description: 'Nůžky růžové – 2 ks',
          categoryType: 'Operations',
          sapNumber: '000000000300000273',
          supplierArticleNumber: 'NUZ-RUZ-02',
          unitOfMeasure: 'Balení',
          unitPrice: 139,
          isFavorite: false,
          contract: 'SMLOUVA-2024-032',
          externalUrl: '',
          attachments: [],
        },
        {
          id: '0dcac46e-6c18-43e6-b7ff-f8ed42dfb38b',
          description: 'Macbook Pro',
          categoryType: 'ItGoodsAndServices',
          sapNumber: 'SAP987654321',
          supplierArticleNumber: 'APP-MBP-16-M2',
          unitOfMeasure: 'Ks',
          unitPrice: 45300,
          isFavorite: true,
          contract: 'SMLOUVA-2024-085',
          externalUrl: 'https://apple.com/macbook-pro',
          attachments: [
            {
              id: 'f3a85f64-5717-4562-b3fc-2c963f66a123',
              name: 'macbook-specs.pdf',
            },
          ],
        },
        {
          id: 'ca8gd723-df10-5164-b567-d32bgb67d474',
          description: 'Letáky A5 barevné',
          categoryType: 'Operations',
          sapNumber: 'SAP987654321',
          supplierArticleNumber: 'LTK-A5-CLR',
          unitOfMeasure: 'Balení',
          unitPrice: 1200,
          isFavorite: true,
          contract: 'SMLOUVA-2024-118',
          externalUrl: '',
          attachments: [],
        },
        {
          id: 'eb9he834-ef21-6275-c678-e43cgc78e585',
          description: 'Roll-up banner',
          categoryType: 'Operations',
          sapNumber: 'SAP456789123',
          supplierArticleNumber: 'RUB-200',
          unitOfMeasure: 'Ks',
          unitPrice: 2500,
          isFavorite: false,
          contract: 'SMLOUVA-2024-118',
          externalUrl: '',
          attachments: [],
        },
        {
          id: 'he2lk167-hi54-9508-f901-h65flk01h818',
          description: 'Kancelářský papír A4',
          categoryType: 'Operations',
          sapNumber: 'SAP543876109',
          supplierArticleNumber: 'PAP-A4-80',
          unitOfMeasure: 'Balík',
          unitPrice: 125,
          isFavorite: true,
          contract: 'SMLOUVA-2024-032',
          externalUrl: '',
          attachments: [],
        },
        {
          id: 'if3ml278-ij65-0619-g012-i76gml12i929',
          description: 'Pořadače A4',
          categoryType: 'Operations',
          sapNumber: 'SAP654987210',
          supplierArticleNumber: 'POR-A4-80',
          unitOfMeasure: 'Ks',
          unitPrice: 85,
          isFavorite: false,
          contract: 'SMLOUVA-2024-032',
          externalUrl: '',
          attachments: [],
        },
        {
          id: 'jg4nm389-jk76-1720-h123-j87hnm23j030',
          description: 'Fixy CENTROPEN sada 10ks',
          categoryType: 'Operations',
          sapNumber: 'SAP765098321',
          supplierArticleNumber: 'FIX-CP-10',
          unitOfMeasure: 'Sada',
          unitPrice: 150,
          isFavorite: false,
          contract: 'SMLOUVA-2024-032',
          externalUrl: '',
          attachments: [],
        },
        {
          id: 'li6op501-lm87-2831-i234-l09jpo45l252',
          description: 'Laserová tiskárna HP Color LaserJet Pro M479fdw',
          categoryType: 'ItGoodsAndServices',
          sapNumber: 'SAP876543210',
          supplierArticleNumber: 'HP-CLJ-M479FDW',
          unitOfMeasure: 'Ks',
          unitPrice: 12500,
          isFavorite: true,
          contract: 'SMLOUVA-2024-085',
          externalUrl: 'https://hp.com/printers/colorlaserjet-m479fdw',
          attachments: [
            {
              id: 'g4b96g75-6828-5673-c4gd-3d074g77bfa7',
              name: 'hp-printer-manual.pdf',
            },
          ],
        },
        {
          id: 'mj7pq612-lm98-3942-k345-m10kqp56m363',
          description: 'Náhradní tonery HP 415A set',
          categoryType: 'ItGoodsAndServices',
          sapNumber: 'SAP987654321',
          supplierArticleNumber: 'HP-415A-SET',
          unitOfMeasure: 'Sada',
          unitPrice: 6800,
          isFavorite: false,
          contract: 'SMLOUVA-2024-085',
          externalUrl: 'https://hp.com/supplies/415a-toner',
          attachments: [],
        },
        {
          id: 'nk8qr723-mn09-4053-l456-n21lrq67n474',
          description: 'Monitor Dell UltraSharp 27"',
          categoryType: 'ItGoodsAndServices',
          sapNumber: 'SAP098765432',
          supplierArticleNumber: 'DELL-U2719D',
          unitOfMeasure: 'Ks',
          unitPrice: 8900,
          isFavorite: true,
          contract: 'SMLOUVA-2024-085',
          externalUrl: 'https://dell.com/monitors/ultrasharp-27',
          attachments: [],
        },
        {
          id: 'ol9rs834-no10-5164-m567-o32msr78o585',
          description: 'Klávesnice Logitech MX Keys',
          categoryType: 'ItGoodsAndServices',
          sapNumber: 'SAP109876543',
          supplierArticleNumber: 'LOG-MX-KEYS',
          unitOfMeasure: 'Ks',
          unitPrice: 2700,
          isFavorite: false,
          contract: 'SMLOUVA-2024-085',
          externalUrl: 'https://logitech.com/mx-keys',
          attachments: [],
        },
        {
          id: 'pm0st945-op21-6275-n678-p43nts89p696',
          description: 'Myš Logitech MX Master 3',
          categoryType: 'ItGoodsAndServices',
          sapNumber: 'SAP210987654',
          supplierArticleNumber: 'LOG-MX-MASTER3',
          unitOfMeasure: 'Ks',
          unitPrice: 2200,
          isFavorite: true,
          contract: 'SMLOUVA-2024-085',
          externalUrl: 'https://logitech.com/mx-master-3',
          attachments: [],
        },
      ],
    },
  },
  error: {
    state: 'Error',
    messages: [
      {
        severity: 'Error',
        code: 'CAT_ERR_001',
        data: { reason: 'Failed to fetch catalogue data' },
      },
    ],
    payload: null,
  },
};
