module.exports = {
  success: {
    payload: {
      id: '29270e33-22eb-433a-9a9b-2b0693c1fc78',
      createdAtUtc: '2025-06-22T01:02:03.091Z',
      createdBy: {
        id: null,
        givenName: 'Pavel',
        surname: 'Fuchs',
        email: '',
        phoneNumber: '',
        defaultAddress: {
          id: 'a11324a1-427e-4ae5-8794-a45018d2ec4d',
          workplaceCode: '0226',
          description: 'Územní pracoviště Mladá Boleslav',
        },
        department: {
          id: '02c6e67b-6909-4d0c-b7fa-616b8059a1e9',
          code: '123',
          description: 'Regionální pobočka Ostrava',
        },
        costCenter: {
          id: 'a584d7d0-cfb4-4f59-ac91-3d0448ee004c',
          code: '980025',
          description: '98 Ústředí URIIT',
        },
        order: {
          id: '92b606f3-9f56-483a-a6a1-b2fdf5ef3b2c',
          code: '26000223',
          description: 'ÚS98 - Odb. business analýzy nových IS',
        },
      },
      requestNumber: null,
      recipient: {
        id: null,
        givenName: 'Pavel',
        surname: 'Fuchs',
        email: '',
        phoneNumber: '',
        defaultAddress: {
          id: 'a11324a1-427e-4ae5-8794-a45018d2ec4d',
          workplaceCode: '0226',
          description: 'Územní pracoviště Mladá Boleslav',
        },
        department: {
          id: '02c6e67b-6909-4d0c-b7fa-616b8059a1e9',
          code: '123',
          description: 'Regionální pobočka Ostrava',
        },
        costCenter: {
          id: 'a584d7d0-cfb4-4f59-ac91-3d0448ee004c',
          code: '980025',
          description: '98 Ústředí URIIT',
        },
        order: {
          id: '92b606f3-9f56-483a-a6a1-b2fdf5ef3b2c',
          code: '26000223',
          description: 'ÚS98 - Odb. business analýzy nových IS',
        },
      },
      submitedAtUtc: null,
      deliveryAddress: {
        id: 'a11324a1-427e-4ae5-8794-a45018d2ec4d',
        workplaceCode: '0226',
        description: 'Územní pracoviště Mladá Boleslav',
      },
      costCenter: {
        id: 'a584d7d0-cfb4-4f59-ac91-3d0448ee004c',
        code: '980025',
        description: '98 Ústředí URIIT',
      },
      order: {
        id: '92b606f3-9f56-483a-a6a1-b2fdf5ef3b2c',
        code: '26000223',
        description: 'ÚS98 - Odb. business analýzy nových IS',
      },
      description: '',
      justification: 'nástup nového zaměstnance',
      isWatching: false,
      wfState: 'Draft',
      approver: null,
      items: [
        {
          id: '8dbc5dc5-a378-4da0-b73c-126424b0ae57',
          purchaserNote: '',
          catalogueItem: {
            id: 'ba7fc612-ce09-4053-a456-c21afa56c363',
            description: 'Nůžky',
            categoryType: 'Operations',
            sapNumber: 'SAP123456789',
            supplierArticleNumber: '',
            unitOfMeasure: 'Ks',
            unitPrice: 239.5,
            isFavorite: false,
            contract: '',
            externalUrl: '',
            attachments: [],
          },
          manualItem: null,
          quantity: 1,
          wfState: 'Active',
          description: '',
          justification: null,
          attachments: [],
        },
        {
          id: '201d651f-5839-4a1c-b4e1-0d5b87a12476',
          purchaserNote: '',
          catalogueItem: null,
          manualItem: {
            id: '7dca14f3-3482-4a31-86c4-79e0cc77c0e6',
            description: 'Oprava židle',
            categoryType: 'Maintenance',
            sapNumber: '',
            supplierArticleNumber: '',
            unitOfMeasure: '',
            unitPrice: 0,
            isFavorite: false,
            contract: '',
            externalUrl: '',
            attachments: [],
          },
          quantity: 0,
          wfState: 'Active',
          description: '',
          justification: 'ulomená noha',
          attachments: [],
        },
        {
          id: '206d555f-706f-4b7f-aecb-e9ea084a40d9',
          purchaserNote: '',
          catalogueItem: {
            id: '0dcac46e-6c18-43e6-b7ff-f8ed42dfb38b',
            description: 'Macbook Pro',
            categoryType: 'ItGoodsAndServices',
            sapNumber: 'SAP123456789',
            supplierArticleNumber: '',
            unitOfMeasure: '',
            unitPrice: 45300,
            isFavorite: false,
            contract: '',
            externalUrl: '',
            attachments: [],
          },
          manualItem: null,
          quantity: 1,
          wfState: 'Active',
          description: '',
          justification: null,
          attachments: [],
        },
      ],
    },
    state: 'Success',
    messages: [],
  },
  error: {
    state: 'error',
    messages: [
      {
        severity: 'Error',
        code: 'REQ_ERR_002',
        data: { reason: 'Request not found' },
      },
    ],
  },
};
