trigger:
- main

resources:
  repositories:
    - repository: workspace
      type: git
      name: workspace
      ref: main

stages:

- stage: build
  pool: 'NisDev1'
  displayName: Build storybook

  jobs:
  - job: build
    displayName: Build storybook

    steps:

    - checkout: workspace
      displayName: Checkout workspace

    - checkout: self
      displayName: Checkout self
      fetchDepth: '0'
      workspaceRepo: true

    - task: gitversion/setup@3
      displayName: 'Setup GitVersion'
      inputs:
        versionSpec: '6.0.x'

    - task: gitversion/execute@3
      displayName: Determine Version
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)'
        useConfigFile: true
        configFilePath: $(Agent.BuildDirectory)/s/workspace/resources/pipelines/gitversion.yml

    - task: NodeTool@0
      inputs:
        versionSpec: '20.18.0'
      displayName: 'Install Node.js'

    - task: npmAuthenticate@0
      displayName: 'Authenticate to Azure Artifacts feed'
      inputs:
        workingFile: .npmrc

    - script: |
        npm install
      displayName: 'npm install'

    - script: |
        npm run storybook:build
      displayName: 'npm run storybook:build'

    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(System.DefaultWorkingDirectory)'
        contents: |
          storybook-static/**
        targetFolder: '$(Build.ArtifactStagingDirectory)'    
      displayName: 'Copy storybook files'

    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(System.DefaultWorkingDirectory)'
        contents: |
          resources/storybook/staticwebapp.config.json
        targetFolder: '$(Build.ArtifactStagingDirectory)/storybook-static'
        flattenFolders: true   
      displayName: 'Copy staticwebapp.config.json file'

    - publish: $(Build.ArtifactStagingDirectory)/storybook-static
      artifact: storybook
      displayName: 'Publish storybook artifact'

- stage: deploy_dev1
  pool: 'NisDev1'
  displayName: Deploy to swa-vzp-dev1-we-001
  dependsOn: build
  condition: succeeded()
    
  jobs:
  - deployment: deploy
    displayName: Deploy
    environment: swa-vzp-dev1-we-001
    variables:
    - group: swa-vzp-dev1-we-001
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: none

          - download: current
            artifact: storybook
            displayName: 'Download storybook artifact'
  
          - task: AzureStaticWebApp@0
            displayName: Deploy to swa-vzp-dev1-we-001 environment
            inputs:
              app_location: '/'
              api_location: ''
              skip_app_build: true
              skip_api_build: true
              is_static_export: true
              verbose: true
              output_location: ''
              azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
              workingDirectory: $(Pipeline.Workspace)/storybook

- stage: deploy_test1
  pool: 'NisTest1'
  displayName: Deploy to swa-vzp-test1-we-001
  dependsOn: deploy_dev1
  condition: succeeded()
    
  jobs:
  - deployment: deploy
    displayName: Deploy
    environment: swa-vzp-test1-we-001
    variables:
    - group: swa-vzp-test1-we-001
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: none

          - download: current
            artifact: storybook
            displayName: 'Download storybook artifact'
  
          - task: AzureStaticWebApp@0
            displayName: Deploy to swa-vzp-test1-we-001 environment
            inputs:
              app_location: '/'
              api_location: ''
              skip_app_build: true
              skip_api_build: true
              is_static_export: true
              verbose: true
              output_location: ''
              azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
              workingDirectory: $(Pipeline.Workspace)/storybook
