trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - 'README.md'
    - '.editorconfig'
    - '.gitattributes'
    - '.gitignore'
    - 'Dockerfile'
    - 'resources/entryendpoint.sh'
    - 'resources/helm/*'
    - 'resources/pipelines/*'

pr: none

variables:
- name: buildConfiguration
  value: 'Release' 
- name: imageRepository
  value: 'nis/component-feedback-hub'
- name: namespace
  value: nis
- group: aks-vzp-dev1-we-001

resources:
  repositories:
    - repository: workspace
      type: git
      name: workspace
      ref: main
    - repository: wiki
      type: git
      name: NIS/NIS.wiki
      ref: wikiMaster
      
stages:

- stage: build
  pool: 'NisDev1'
  displayName: Build
  isSkippable: false

  jobs:
  - job: build
    displayName: Build

    steps: 
    - checkout: workspace
    - template: resources/pipelines/steps/dotnet-build.yaml@workspace
    - template: resources/pipelines/steps/dotnet-documentation.yaml@workspace
    - template: resources/pipelines/steps/dotnet-package.yaml@workspace
    - template: resources/pipelines/steps/dotnet-docker.yaml@workspace

    - publish: $(Agent.BuildDirectory)/s/workspace/resources/helm
      artifact: helm
      displayName: 'Publish helm artifact'

    - publish: $(Agent.BuildDirectory)/s/$(Build.Repository.Name)/resources/helm
      artifact: values
      displayName: 'Publish values artifact'

- stage: deploy_dev1
  pool: 'NisDev1'
  displayName: Deploy to aks-vzp-dev1-we-001
  dependsOn: build
  condition: succeeded()
  variables:
    - name: tag
      value: $[ stageDependencies.build.build.outputs['GitVersionExecute.SemVer'] ]
    - group: aks-vzp-dev1-we-001
    
  jobs:
  - deployment: deploy
    displayName: Deploy
    environment: aks-vzp-dev1-we-001
    variables:
    - group: aks-vzp-dev1-we-001-component-feedback-hub
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: none

          - download: current
            artifact: helm
            displayName: 'Download helm artifact'

          - download: current
            artifact: values
            displayName: 'Download values artifact'

          - task: HelmDeploy@1
            displayName: Helm upgrade
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: $(azureSubscriptionConnection)
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)   
              namespace: $(namespace)
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(Pipeline.Workspace)/helm/nis/'
              releaseName: '$(Build.Repository.Name)'
              overrideValues: 'image.repository=$(containerRegistry)/$(imageRepository),image.tag=$(tag),secretProviderClass.parameters.keyvaultName=$(secretProviderClassParametersKeyvaultName),secretProviderClass.parameters.tenantId=$(secretProviderClassParametersTenantId),secretProviderClass.parameters.userAssignedIdentityID=$(secretProviderClassParametersUserAssignedIdentityID)'
              valueFile: '$(Pipeline.Workspace)/values/values.yaml'

- stage: deploy_test1
  pool: 'NisTest1'
  displayName: Deploy to aks-vzp-test1-we-001
  dependsOn:
  - build
  - deploy_dev1
  condition: succeeded()
  variables:
    - name: tag
      value: $[ stageDependencies.build.build.outputs['GitVersionExecute.SemVer'] ]
    - group: aks-vzp-test1-we-001
    
  jobs:
  - deployment: deploy
    displayName: Deploy
    environment: aks-vzp-test1-we-001
    variables:
    - group: aks-vzp-test1-we-001-component-feedback-hub
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: none

          - download: current
            artifact: helm
            displayName: 'Download helm artifact'

          - download: current
            artifact: values
            displayName: 'Download values artifact'

          - task: Docker@2
            displayName: "Docker login for pull"
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnectionPull)'
              command: login

          - script: |
              docker pull $(containerRegistryPull)/$(imageRepository):$(tag)
              docker tag $(containerRegistryPull)/$(imageRepository):$(tag) $(containerRegistry)/$(imageRepository):$(tag)
            displayName: Docker pull and tag

          - task: Docker@2
            displayName: "Docker login for push"
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              command: login
  
          - script: |
              docker push $(containerRegistry)/$(imageRepository):$(tag)
            displayName: Docker push

          - task: HelmDeploy@1
            displayName: Helm upgrade
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: $(azureSubscriptionConnection)
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)   
              namespace: $(namespace)
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(Pipeline.Workspace)/helm/nis/'
              releaseName: '$(Build.Repository.Name)'
              overrideValues: 'image.repository=$(containerRegistry)/$(imageRepository),image.tag=$(tag),secretProviderClass.parameters.keyvaultName=$(secretProviderClassParametersKeyvaultName),secretProviderClass.parameters.tenantId=$(secretProviderClassParametersTenantId),secretProviderClass.parameters.userAssignedIdentityID=$(secretProviderClassParametersUserAssignedIdentityID)'
              valueFile: '$(Pipeline.Workspace)/values/values-test1.yaml'
