trigger: none

pr: none

variables:
- name: imageRepository
  value: 'nis/frontend-nis'
- name: namespace
  value: nis
- group: aks-vzp-stage-we-001

resources:
  pipelines:
  - pipeline: source-pipeline
    source: frontend-nis-ci-cd
    trigger: none  

stages:

- stage: deploy_stage
  pool: 'NisStage'
  displayName: Deploy to aks-vzp-stage-we-001
  condition: eq(variables['resources.pipeline.source-pipeline.SourceBranch'], 'refs/heads/main')
  isSkippable: false
  variables:
    - name: tag
      value: $(resources.pipeline.source-pipeline.runName)
    - group: aks-vzp-stage-we-001
    
  jobs:
  - deployment: deploy
    displayName: Deploy
    environment: aks-vzp-stage-we-001
    variables:
    - group: aks-vzp-stage-we-001-frontend-nis
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: none

          - download: source-pipeline
            artifact: helm
            displayName: 'Download helm artifact'

          - download: source-pipeline
            artifact: values
            displayName: 'Download values artifact'

          - task: Docker@2
            displayName: "Docker login for pull"
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnectionPull)'
              command: login

          - script: |
              docker pull $(containerRegistryPull)/$(imageRepository):$(tag)
              docker tag $(containerRegistryPull)/$(imageRepository):$(tag) $(containerRegistry)/$(imageRepository):$(tag)
            displayName: Docker pull and tag

          - task: Docker@2
            displayName: "Docker login for push"
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              command: login
  
          - script: |
              docker push $(containerRegistry)/$(imageRepository):$(tag)
            displayName: Docker push

          - task: HelmDeploy@1
            displayName: Helm upgrade
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: $(azureSubscriptionConnection)
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)   
              namespace: $(namespace)
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(Pipeline.Workspace)/source-pipeline/helm/nis/'
              releaseName: '$(Build.Repository.Name)'
              overrideValues: 'image.repository=$(containerRegistry)/$(imageRepository),image.tag=$(tag),ingress.annotations.kubernetes\.azure\.com/tls-cert-keyvault-uri=$(ingressAnnotationsKubernetesAzureComTlsCertKeyvaultUri),secretProviderClass.parameters.keyvaultName=$(secretProviderClassParametersKeyvaultName),secretProviderClass.parameters.tenantId=$(secretProviderClassParametersTenantId),secretProviderClass.parameters.userAssignedIdentityID=$(secretProviderClassParametersUserAssignedIdentityID)'
              valueFile: '$(Pipeline.Workspace)/source-pipeline/values/values-stage.yaml'

- stage: deploy_prod
  pool: 'NisProd'
  displayName: Deploy to aks-vzp-prod-we-001
  condition: eq(variables['resources.pipeline.source-pipeline.SourceBranch'], 'refs/heads/main')
  variables:
    - name: tag
      value: $(resources.pipeline.source-pipeline.runName)
    - group: aks-vzp-prod-we-001
    
  jobs:
  - deployment: deploy
    displayName: Deploy
    environment: aks-vzp-prod-we-001
    variables:
    - group: aks-vzp-prod-we-001-frontend-nis
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: none

          - download: source-pipeline
            artifact: helm
            displayName: 'Download helm artifact'

          - download: source-pipeline
            artifact: values
            displayName: 'Download values artifact'

          - task: Docker@2
            displayName: "Docker login for pull"
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnectionPull)'
              command: login

          - script: |
              docker pull $(containerRegistryPull)/$(imageRepository):$(tag)
              docker tag $(containerRegistryPull)/$(imageRepository):$(tag) $(containerRegistry)/$(imageRepository):$(tag)
            displayName: Docker pull and tag

          - task: Docker@2
            displayName: "Docker login for push"
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              command: login
  
          - script: |
              docker push $(containerRegistry)/$(imageRepository):$(tag)
            displayName: Docker push

          - task: HelmDeploy@1
            displayName: Helm upgrade
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: $(azureSubscriptionConnection)
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)   
              namespace: $(namespace)
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(Pipeline.Workspace)/source-pipeline/helm/nis/'
              releaseName: '$(Build.Repository.Name)'
              overrideValues: 'image.repository=$(containerRegistry)/$(imageRepository),image.tag=$(tag),ingress.annotations.kubernetes\.azure\.com/tls-cert-keyvault-uri=$(ingressAnnotationsKubernetesAzureComTlsCertKeyvaultUri),secretProviderClass.parameters.keyvaultName=$(secretProviderClassParametersKeyvaultName),secretProviderClass.parameters.tenantId=$(secretProviderClassParametersTenantId),secretProviderClass.parameters.userAssignedIdentityID=$(secretProviderClassParametersUserAssignedIdentityID)'
              valueFile: '$(Pipeline.Workspace)/source-pipeline/values/values-prod.yaml'
